---
name: Manage - Sync branches

"on":
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'


permissions:
  contents: read


jobs:
  update_external_airflow_fork:
    name: Sync branch archive with origin
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Generate app token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1  # v3.2.0
        id: generate-token
        with:
          app-id: ${{ secrets.GH_APP_SRP_ID }}
          private-key: ${{ secrets.GH_APP_SRP_PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          fetch-depth: 0

      - name: Synchronize the given branch
        uses: TobKed/github-forks-sync-action@2fb78daa46a630ff56455a63dec51ff00ba56e23  # v0.4.0
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          upstream_repository: hardware/selfoss
          target_repository: ${{ github.repository }}
          upstream_branch: master
          target_branch: archive
          force: false
          tags: false
